### ISSUE TITLE
Add axis-label rotate

### ISSUE THREAD

**Issue by berry** [kkpoon/elm-echarts#8]
Hi @kkpoon, there are not many Elm libraries to quickly add charts to an Elm app. Yours is one of the few options. Especially since the update to Elm 0.19. I am currently using your Elm package. I know that Echarts has a very large API. But, I would like to be able to rotate the labels on the x-axis. See: https://ecomfe.github.io/echarts-doc/public/en/option.html#xAxis.axisLabel.rotate. Could you add this to your library? Thank you very much in advance. Maybe, I will add the option myself and send you a pull request. But, I have to find some time to do it ;-)

**Comment by kkpoon** [comment]
hi @berry. Thank for the suggestion

I have added some of the options for axisLabel. Are these options good for your case?

If it is good, I will merge it and publish a new version.

**Comment by berry** [comment]
Hi @kkpoon, I looked at the changes for axisLabel and the options you build in are more than adequate for my use case. This will help me a lot. Thank you very much for responding so quickly.

**Comment by kkpoon** [comment]
@berry it is published as version 10.0.0

**Comment by berry** [comment]
Hi @kkpoon, I tested the code, but it did not work. I looked at the source code and the function call to encodeAxisLabel is missing in encodeXAxisOption en encodeYAxisOption. So, axisLabel does not appear in the html-custom-element. When I reviewed your code I also missed this. Sorry.

**Comment by kkpoon** [comment]
Hi @berry , Do you have any idea to fix this? I am lack of time to find the solution at this moment.

**Comment by berry** [comment]
Hi @kkpoon, I think so. I will try to create a pull request over the weekend.

**Comment by kkpoon** [comment]
Published version 10.0.1

**Comment by kkpoon** [comment]
Hi @berry , shall we close this issue?

Thanks

**Comment by berry** [comment]
Yes. Please.
